# Generated by Django 4.2.23 on 2025-07-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.PositiveIntegerField(choices=[(60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes'), (150, '150 minutes'), (180, '180 minutes')], default=60),
        ),
    ]
