# Generated by Django 4.2.23 on 2025-07-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_order_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
