# Generated by Django 4.2.23 on 2025-07-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_voucher_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled_by_user', 'Cancelled by User'), ('cancelled_by_admin', 'Cancelled by Admin'), ('completed', 'Completed')], default='pending', max_length=32),
        ),
    ]
